### ISSUE TITLE
New version 1.2.1

### ISSUE THREAD

**Issue by majoballs** [KaOS-Community-Packages/minidlna#1]
Hello
The new version was released on August 24, 2017. Are there any chances to update the application?
Regards

**Comment by fjmorazan** [comment]
Hi @majoballs
KCP is maintained by the community, users like you. KCP has no packagers since nothing in it is packaged, it just consists of scripts that make it possible for you to easily build.
See https://kaosx.us/docs/kcp for more, and anyone can help maintain & update any such script (PKGBUILD) in KCP, including you.

In the case of this package it hasn't been updated the PKGBUILD almost **2 years ago**, so I'll update it **just this time** 😁

**Comment by majoballs** [comment]
Thanks. Good advice, I will definitely learn about this guide.

**Comment by ShalokShalom** [comment]
Here you can find advice if you stock: https://forum.kaosx.us/t/creating-packages-using-kcp
